### PR TITLE
Refactor fileds and a bit of cleanup

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Closes: https://github.com/tintoy/msbuild-project-tools-server/issues/61

- Moved private propertis to fields
- Use common .NET naming rules (e.g. `s_` prefix for static private fields)
- Added `private` modifier to all private fields for consistency
- Removed unnecessary empty constructors
- Removed `IOHelper` class since it was never used

@tintoy PTAL

### CODE REVIEW

**Comment by tintoy** [comment]
Just one thing - constructors vs private fields; are we being explicit or implicit?

**Comment by tintoy** [comment]
BTW, the reason I use explicit constructors (even if empty) is so that adding a constructor later doesn't break anything (since default constructor is only added if there are no other constructors).

**Comment by DoctorKrolic** [comment]
> Just one thing - constructors vs private fields; are we being explicit or implicit?

Can you clarify what do you mean?

> adding a constructor later doesn't break anything

You will immediately get a compiler error if that happens. And even if not, this should be caught by tests and fail in CI

**Comment by tintoy** [comment]
Yeah sorry, that's what I get for commenting with only 2 hours sleep
🙂

I meant that, if we are being explicit with access modifiers (even when they are the default), shouldn't we also be explicit with constructors (even if they are the default)?

I can't remember where I originally started doing the constructor thing (but I think it was part of the original framework design guidelines or similar documentation). As a guess, I probably stuck with it because of cases where the constructor signature forms part of the public API; unlike access modifiers (where they are applied to a given "site" and their effects are mostly local except for overridden children), adding a constructor in one location in the code also has an effect on some other (invisible) location in the type's definition. So no tests need to fail, but simply adding a member (constructor) may wind up breaking binary compatibility. Whether that's applicable here may be somewhat dubious, but I've generally found it easier to just leave them in as a form of documentation (which, now I think about it) is how I imagine people feel about explicit access modifiers. So I'm no longer sure which side I'm arguing for 😂

**Comment by DoctorKrolic** [comment]
> I meant that, if we are being explicit with access modifiers (even when they are the default), shouldn't we also be explicit with constructors (even if they are the default)?

I don't think these 2 should be connected. You see, when you look at member/type without access modifier you should actually think and remember what accessibility is there by default. Thus having accessibility modifiers always in place just simplifies reading thorough code since you don't need to do that in such cases. While if you encounter empty constructor, you start looking for other constructor overloads which again, makes you think in places, where that can be avoided.

> the constructor signature forms part of the public API

We don't expose this project as an open-source library therefore we shouldn't have any responsibilities of maintaining consistent public API, right?

**Comment by tintoy** [comment]
Hmm, tbh I don't find the constructor argument all that convincing (for access modifiers it frees me up so I don't need to think about how private something is but rather how public it is, and not seeing any constructor at all makes me wonder where it is; whether I've just missed seeing it) but I can see that may simply be due to how I think about code when I read it. I don't think there is a "right" answer here; it's more a matter of what is more comfortable for the people who are working with the code day-to-day. At the moment that's you and I (more you than me at this stage) so I think I am ok with it.

As for the public API argument yes, you're correct there, it was just an attempt to explain why I generally maintain the habit (most of my open-source projects are libraries so it's where my head is at most of the time 🙂).

**Comment by tintoy** [comment]
Oh and do we need `s_`? That really does look weird to me (a little close to Hungarian notation for comfort 🙂).

**Comment by tintoy** [comment]
(that in particular feels more on the cosmetic side of refactoring and I'd prefer to stick with functional refactoring of the codebase where possible)

**Comment by tintoy** [comment]
To put it another way - functional refactoring (which is like 95% of the changes you've made over the last couple of weeks) is good, and so is making things consistent, but cosmetic changes (although they may make the code feel more familiar) is more of a marginal proposition.

More generally, my approach to open-source work is this:

When working with an existing codebase I tend to avoid making largely cosmetic changes, preferring to match the project's existing style (unless the code is too inconsistent for there to be any appreciable style to match). That doesn't mean things are set in stone but each cosmetic change has to be weighed up against whether current and future maintainers will feel the same way about them (which I think is harder to measure than it it would be for functional changes).

Hopefully this doesn't come across as me trying to tell you how to think; it's more just an explanation of how I do, so we're on the same page in terms of motivations?

**Comment by tintoy** [comment]
> Oh and do we need `s_`? That really does look weird to me (a little close to Hungarian notation for comfort 🙂).

Actually, having thought some more about this, I feel like I haven't made an adequate case for why singling out static fields is unnecessary. I know I've literally _never_ had a problem where I thought a static field was an instance field but I'll need to have a think about why that is and get back to you (I can see there is a reason but it's pretty much invisible to me these days).

**Comment by DoctorKrolic** [comment]
I'm gonna close this for now to revisit these changes later one by one

**Pull request closed without merging**
