### PR TITLE
Use tab-character in completion text

### PR DESCRIPTION
**Pull request by inosik**
This makes the snippets work much nicer with indentations other than 4 spaces.

### CODE REVIEW

**Comment by tintoy** [comment]
Hi - thanks for contributing!

Will this change still work if spaces are being used? Sorry, not in front of my computer right now or I’d just check for myself :)

**Comment by inosik** [comment]
Yes, I usually use an indentation of 2 spaces in my MSBuild files and I already tried this locally:



But this might also be some behavior which only VS Code has. I'm not sure how other editors would handle this.

**Comment by tintoy** [comment]
No worries, will add a setting for it :)

**Comment by tintoy** [comment]
(with default to tabs)

**Comment by inosik** [comment]
Hey, I wanted to check on this PR. Do you still plan to merge this? Can I do something to get this merged?

**Comment by tintoy** [comment]
Oh, sorry, I must have forgot about this! Doing it now :)

**Comment by tintoy** [comment]
If I build and post a new vsix here, can you try it out for me?

**Comment by inosik** [comment]
Sure 👍🏻

**Comment by tintoy** [comment]
Ok, will build one in the next 10 mins or so :)

**Comment by tintoy** [comment]
Sorry, took a bit longer than expected (my NPM cache was broken). Here you go:

[msbuild-project-tools-0.2.54.vsix.zip](https://github.com/tintoy/msbuild-project-tools-server/files/3024850/msbuild-project-tools-0.2.54.vsix.zip)

**Comment by inosik** [comment]
Works like in the GIF above, thanks!

**Comment by tintoy** [comment]
Great - will publish the new release first thing in the morning :)

**Pull request merged**
