### PR TITLE
Update version of Microsoft.Language.Xml and remove local package source

### PR DESCRIPTION
**Pull request by DoctorKrolic**
I don't know what was the original motivation of having `Microsoft.Language.Xml` package coming from local source, but now it is available on NuGet. Thus I removed local feed (and `Nuget.config` since it's no longer necessary) and updated package version to latest available. As far as I can tell, newer versions of this package are now published as [GuiLabs.Language.Xml](https://www.nuget.org/packages/GuiLabs.Language.Xml), but such brand changes can also mean compatability breaks, so I didn't ugrade to new name. Manually verified in a VS Code extension, that things work well, although it would be much nicer if there were tests guarding us against breaks

### CODE REVIEW

**Comment by tintoy** [comment]
Yeah it wasn't published at the time, but if it's on NuGet now then that's great.

As for tests against breakage, that may be a somewhat Herculean task given that handling of edge-cases is around 90% of why we use that library at all; there are so many interesting ways in which XML can be invalid but (as a language service) we still need to act as if the rest of the XML
is valid 🙂

I'll create a separate ticket to investigate a potential upgrade but unless there are significant improvements it may not be worth the effort of upgrading something that already does what we need it to (at least so far, I've only ever found a single bug in that library, and that's been fixed).

**Comment by tintoy** [comment]
Is the version of `OmniSharp.LSP` that we use also still up on NuGet?

**Comment by DoctorKrolic** [comment]
> handling of edge-cases is around 90% of why we use that library at all; there are so many interesting ways in which XML can be invalid but (as a language service) we still need to act as if the rest of the XML
is valid 🙂

Man, I have merged PRs to roslyn where I improve error recovery in C# compiler's parser. I 100% understand how things work in the language services/compilers world)

> Is the version of `OmniSharp.LSP` that we use also still up on NuGet?

Yes, even before changes in this PR all omnisharp stuff was comming from NuGet. And it is still actively updated. [The latest version 0.19.7](https://www.nuget.org/packages/OmniSharp.Extensions.LanguageProtocol/0.19.7) was published just 7 month ago, which is not that musch

**Comment by tintoy** [comment]
Thanks again!

**Pull request merged**
